Repository antvis/G, pull requests merged in 2019-11, with the labels that each got.

#256 fix(g-canvas): bbox calculation for path is incorrect when angle is 0 and π
  packages/g-canvas/src/util/path.ts
  packages/g-canvas/tests/bugs/issue-254-spec.js
Labels: PR: unreviewed, bug

#251 docs: Upgrade theme config
  docs/api/canvas.en.md
  docs/api/canvas.zh.md
  docs/guide/getting-started.en.md
  docs/guide/getting-started.zh.md
  gatsby-config.js
  package.json
Labels: PR: reviewed-approved, documentation

#258 fix PathCommand define
  packages/g-base/src/types.ts
Labels: PR: reviewed-changes-requested, bug

#242 fix(g-base): cursor attr for shape should be effective
  packages/g-base/src/event/event-contoller.ts
  packages/g-canvas/tests/bugs/issue-233-spec.js
Labels: PR: reviewed-changes-requested, bug

#247 Fix 渐变色动画，虽无补间，但是颜色需要更新。
  .gitignore
  .travis.yml
  src/core/mixin/animation.js
  src/core/mixin/timeline.js
  src/util/index.js
  test/unit/canvas/core/animate-spec.js
  test/unit/canvas/core/event-spec.js
Labels: PR: reviewed-approved

#261 fix: 渐变色无补间，直接赋值
  packages/g-base/src/abstract/element.ts
  packages/g-base/src/animate/timeline.ts
  packages/g-base/src/util/color.ts
  packages/g-base/tests/unit/animate-spec.js
Labels: PR: reviewed-approved, bug

#259 fix(g-canvas): bbox calculation for path with angle should be accurate
  packages/g-canvas/src/util/path.ts
  packages/g-canvas/tests/bugs/issue-232-spec.js
  packages/g-canvas/tests/bugs/issue-252-spec.js
  packages/g-canvas/tests/bugs/issue-254-spec.js
Labels: PR: reviewed-changes-requested, bug

#262 feat(g-base): add some member functions for Group
  packages/g-base/src/abstract/group.ts
  packages/g-base/src/interfaces.ts
  packages/g-base/src/types.ts
  packages/g-base/src/util/group.ts
  packages/g-base/tests/unit/group-spec.js
  packages/g-base/tests/unit/group-util-spec.js
Labels: PR: reviewed-approved, enhancement

#250 feat(g-base): support * for event delegation, add name and delegateObject for event
  packages/g-base/src/abstract/base.ts
  packages/g-base/src/event/event-contoller.ts
  packages/g-base/src/event/graph-event.ts
  packages/g-base/tests/unit/event-spec.js
  packages/g-canvas/tests/bugs/issue-249-spec.js
Labels: PR: reviewed-approved, enhancement

#265 fix(g-canvas): bbox calculation should be correct for path when angle is null, 0 and PI
  packages/g-canvas/src/util/path.ts
  packages/g-canvas/tests/bugs/issue-210-spec.js
  packages/g-canvas/tests/bugs/issue-232-spec.js
  packages/g-canvas/tests/bugs/issue-252-spec.js
  packages/g-canvas/tests/bugs/issue-254-spec.js
Labels: PR: reviewed-approved, bug

#267 fix(g-canvas): stroke attr should be working for Text
  packages/g-canvas/src/shape/text.ts
  packages/g-canvas/tests/bugs/issue-266-spec.js
  packages/g-canvas/tests/get-color.ts
Labels: PR: reviewed-changes-requested, bug

#268 site: g.antv.vision
  docs/api/canvas.en.md
  docs/api/canvas.zh.md
  docs/api/element.en.md
  docs/api/element.zh.md
  docs/api/shape/attrs.en.md
  docs/api/shape/attrs.zh.md
  docs/guide/introduce.en.md
  docs/guide/introduce.zh.md
  docs/guide/release.en.md
  docs/guide/release.zh.md
  examples/event/bubble/index.en.md
  examples/event/delegate/index.en.md
  gatsby-config.js
Labels: PR: reviewed-changes-requested, site

#270 site: git add demo directory in examples
  .gitignore
  examples/animation/attribute/demo/meta.json
  examples/animation/attribute/demo/multiple-attributes.js
  examples/animation/attribute/demo/single-attribute.js
  examples/animation/onFrame/demo/along-circle.js
  examples/animation/onFrame/demo/along-rect.js
  examples/animation/onFrame/demo/basic.js
  examples/animation/onFrame/demo/concurrent.js
  examples/animation/onFrame/demo/meta.json
  examples/animation/onFrame/demo/rotate.js
  examples/event/bubble/demo/basic.js
  examples/event/bubble/demo/meta.json
  examples/event/delegate/demo/basic.js
  examples/event/delegate/demo/meta.json
  examples/event/shape/demo/basic.js
  examples/event/shape/demo/meta.json
  examples/shape/circle/demo/basic.js
  examples/shape/circle/demo/meta.json
  examples/shape/dom/demo/basic.js
  examples/shape/dom/demo/meta.json
  examples/shape/ellipse/demo/basic.js
  examples/shape/ellipse/demo/meta.json
  examples/shape/image/demo/basic.js
  examples/shape/image/demo/meta.json
  examples/shape/line/demo/basic.js
  examples/shape/line/demo/meta.json
  examples/shape/marker/demo/basic.js
  examples/shape/marker/demo/meta.json
  examples/shape/path/demo/basic.js
  examples/shape/path/demo/meta.json
  examples/shape/polygon/demo/basic.js
  examples/shape/polygon/demo/meta.json
  examples/shape/polyline/demo/basic.js
  examples/shape/polyline/demo/meta.json
  examples/shape/rect/demo/basic.js
  examples/shape/rect/demo/meta.json
  examples/shape/text/demo/basic.js
  examples/shape/text/demo/meta.json
Labels: PR: reviewed-changes-requested, site
