Repository antvis/G, pull requests merged in 2019-12, with the labels that each got.

#278 chore: update issue and pull request template
  .github/----please-use-antv-issue-helper---.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: unreviewed, chore

#277 fix(g-svg): group.addShape should work when group dom is not created
  packages/g-svg/src/canvas.ts
  packages/g-svg/src/group.ts
  packages/g-svg/src/shape/base.ts
  packages/g-svg/src/util/dom.ts
  packages/g-svg/src/util/draw.ts
  packages/g-svg/tests/bugs/issue-276-spec.js
Labels: PR: unreviewed, bug

#279 fix(g-base): animation should work when interpolate for null matrix
  packages/g-base/src/animate/timeline.ts
  packages/g-canvas/tests/bugs/issue-273-spec.js
Labels: PR: unreviewed, bug

#271 feat: 通过属性配置Text shape绘制的max width
  __tests__/unit/canvas/shape/text-spec.js
  src/shapes/text.ts
Labels: PR: reviewed-approved, enhancement

#285 fix(g-svg): el maybe undefined when calculate bbox
  packages/g-svg/src/shape/base.ts
  packages/g-svg/tests/bugs/issue-276-spec.js
Labels: PR: reviewed-changes-requested, bug

#280 refactor(g-math): complete typescript types
  packages/g-math/src/arc.ts
  packages/g-math/src/bezier.ts
  packages/g-math/src/circle.ts
  packages/g-math/src/cubic.ts
  packages/g-math/src/ellipse.ts
  packages/g-math/src/line.ts
  packages/g-math/src/polygon.ts
  packages/g-math/src/polyline.ts
  packages/g-math/src/quadratic.ts
  packages/g-math/src/rect.ts
  packages/g-math/src/segments.ts
  packages/g-math/src/types.ts
  packages/g-math/src/util.ts
Labels: PR: reviewed-approved, refactor

#297 fix(g-canvas): should render correctly when start point and end point are same for arc
  packages/g-canvas/src/util/arc-params.ts
  packages/g-canvas/src/util/path.ts
  packages/g-canvas/src/util/util.ts
  packages/g-canvas/tests/bugs/issue-287-spec.js
Labels: PR: reviewed-changes-requested, bug

#299 fix(g-canvas): strokeText should be invoked before fillText for Text
  packages/g-canvas/src/shape/text.ts
  packages/g-canvas/tests/bugs/issue-273-spec.js
  packages/g-canvas/tests/bugs/issue-298-spec.js
Labels: PR: unreviewed, bug

#304 feat(g-base): add findAllByName function for Group
  docs/api/group.en.md
  docs/api/group.zh.md
  packages/g-base/src/abstract/group.ts
  packages/g-base/src/interfaces.ts
  packages/g-base/tests/unit/group-spec.js
Labels: PR: unreviewed, enhancement

#306 fix(canvas): marker should be compatiable with r attr
  src/shapes/marker.js
  test/bugs/issue-305-spec.js
Labels: PR: unreviewed, bug

#307 feat(g-canvas & g-svg): add getTotalLength method for path
  docs/api/shape/api.en.md
  docs/api/shape/path.en.md
  docs/api/shape/path.zh.md
  packages/g-base/src/index.ts
  packages/g-base/src/util/path.ts
  packages/g-canvas/src/shape/path.ts
  packages/g-canvas/src/util/path.ts
  packages/g-canvas/tests/unit/shape/path-spec.js
  packages/g-svg/src/shape/path.ts
  packages/g-svg/tests/unit/shape/path-spec.js
Labels: PR: unreviewed, enhancement

#309 feat(g-canvas & g-svg): add getPoint method for Path
  docs/api/shape/path.en.md
  docs/api/shape/path.zh.md
  examples/animation/onFrame/demo/along-path.js
  examples/animation/onFrame/demo/meta.json
  packages/g-canvas/src/shape/path.ts
  packages/g-canvas/tests/unit/shape/path-spec.js
  packages/g-svg/src/shape/path.ts
  packages/g-svg/tests/unit/shape/path-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#310 feat(g-canvas & g-svg): add getTotalLength and getPoint method for Line
  docs/api/shape/line.en.md
  docs/api/shape/line.zh.md
  examples/animation/onFrame/demo/along-line.js
  examples/animation/onFrame/demo/meta.json
  packages/g-canvas/src/shape/line.ts
  packages/g-canvas/src/shape/path.ts
  packages/g-canvas/tests/unit/shape/line-spec.js
  packages/g-canvas/tests/unit/shape/path-spec.js
  packages/g-svg/package.json
  packages/g-svg/src/shape/line.ts
  packages/g-svg/src/shape/path.ts
  packages/g-svg/tests/unit/shape/line-spec.js
  packages/g-svg/tests/unit/shape/path-spec.js
Labels: PR: unreviewed, enhancement

#311 docs: 🔍 Add algolia docsearchOptions
  gatsby-config.js
  package.json
Labels: PR: reviewed-changes-requested, documentation

#300 feat(g-base): add emitDelegation method for Element
  docs/api/element.en.md
  docs/api/element.zh.md
  packages/g-base/src/abstract/element.ts
  packages/g-base/src/event/event-contoller.ts
  packages/g-base/src/interfaces.ts
  packages/g-base/tests/unit/element-spec.js
  packages/g-base/tests/unit/event-spec.js
Labels: PR: unreviewed, enhancement

#303 feat(g-base): add getRenderer method for canvas
  .eslintignore
  .gitignore
  docs/api/canvas.en.md
  docs/api/canvas.zh.md
  packages/g-base/src/abstract/canvas.ts
  packages/g-base/src/interfaces.ts
  packages/g-base/src/types.ts
  packages/g-canvas/src/canvas.ts
  packages/g-canvas/tests/unit/canvas-spec.js
  packages/g-svg/src/canvas.ts
  packages/g-svg/tests/unit/canvas-spec.js
Labels: PR: unreviewed, enhancement

#312 feat(g-canvas & g-svg): add getTotalLength and getPoint method for Polyline
  docs/api/shape/polyline.en.md
  docs/api/shape/polyline.zh.md
  examples/animation/attribute/API.en.md
  examples/animation/attribute/API.zh.md
  examples/animation/onFrame/API.en.md
  examples/animation/onFrame/API.zh.md
  examples/animation/onFrame/demo/meta.json
  examples/animation/path/demo/along-circle.js
  examples/animation/path/demo/along-line.js
  examples/animation/path/demo/along-path.js
  examples/animation/path/demo/along-polyline.js
  examples/animation/path/demo/along-rect.js
  examples/animation/path/demo/meta.json
  examples/animation/path/index.en.md
  examples/animation/path/index.zh.md
  packages/g-canvas/src/shape/polyline.ts
  packages/g-canvas/tests/unit/shape/polyline-spec.js
  packages/g-svg/src/shape/polyline.ts
  packages/g-svg/tests/unit/shape/polyline-spec.js
Labels: PR: unreviewed, enhancement

#315 docs(demo): modify the import of G
  examples/animation/attribute/demo/multiple-attributes.js
  examples/animation/attribute/demo/single-attribute.js
  examples/animation/onFrame/demo/basic.js
  examples/animation/onFrame/demo/concurrent.js
  examples/animation/onFrame/demo/rotate.js
  examples/animation/path/demo/along-circle.js
  examples/animation/path/demo/along-line.js
  examples/animation/path/demo/along-path.js
  examples/animation/path/demo/along-polyline.js
  examples/animation/path/demo/along-rect.js
  examples/event/bubble/demo/basic.js
  examples/event/delegate/demo/basic.js
  examples/event/shape/demo/basic.js
  examples/shape/circle/demo/basic.js
  examples/shape/dom/demo/basic.js
  examples/shape/ellipse/demo/basic.js
  examples/shape/image/demo/basic.js
  examples/shape/line/demo/basic.js
  examples/shape/marker/demo/basic.js
  examples/shape/path/demo/basic.js
  examples/shape/polygon/demo/basic.js
  examples/shape/polyline/demo/basic.js
  examples/shape/rect/demo/basic.js
  examples/shape/text/demo/basic.js
  gatsby-browser.js
Labels: PR: unreviewed, documentation

#320 feat(g-base): add getCursor() and setCursor(cursor) method for Canvas
  docs/api/canvas.en.md
  docs/api/canvas.zh.md
  packages/g-base/src/abstract/canvas.ts
  packages/g-base/src/event/event-contoller.ts
  packages/g-base/src/interfaces.ts
  packages/g-base/src/types.ts
  packages/g-canvas/tests/bugs/issue-319-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#318 fix(g-base): setClip should work when shape not mounted under canvas
  docs/api/canvas.en.md
  docs/api/canvas.zh.md
  docs/api/general/element.en.md
  docs/api/general/element.zh.md
  docs/api/group.en.md
  docs/api/group.zh.md
  packages/g-base/src/abstract/container.ts
  packages/g-base/src/abstract/element.ts
  packages/g-base/src/interfaces.ts
  packages/g-base/tests/unit/element-spec.js
  packages/g-canvas/src/shape/base.ts
  packages/g-canvas/src/shape/index.ts
  packages/g-canvas/tests/bugs/issue-317-spec.js
  packages/g-canvas/tests/unit/canvas-spec.js
  packages/g-canvas/tests/unit/group-spec.js
  packages/g-canvas/tests/unit/shape/base-spec.js
  packages/g-svg/src/shape/base.ts
  packages/g-svg/src/shape/index.ts
  packages/g-svg/tests/unit/canvas-spec.js
  packages/g-svg/tests/unit/group-spec.js
  packages/g-svg/tests/unit/shape/base-spec.js
Labels: PR: unreviewed, bug

#324 fix(g-canvas): matrix animation for clip should work
  packages/g-base/package.json
  packages/g-base/src/animate/timeline.ts
  packages/g-canvas/src/canvas.ts
  packages/g-canvas/src/group.ts
  packages/g-canvas/src/shape/base.ts
  packages/g-canvas/src/util/draw.ts
  packages/g-canvas/tests/bugs/issue-323-spec.js
Labels: PR: unreviewed, bug

#327 fix(g-canvas): partial rendering for arc path should be correct when rx or ry is 0
  packages/g-base/src/event/graph-event.ts
  packages/g-base/tests/unit/event-spec.js
  packages/g-canvas/src/util/arc-params.ts
  packages/g-canvas/tests/bugs/issue-326-spec.js
Labels: PR: reviewed-approved, bug

#328 fix(module): add module entry to avoid jest sourcemap is empty
  packages/g-base/package.json
  packages/g-math/package.json
Labels: PR: reviewed-approved, bug

#329 feat(g-canvas & g-svg): add getStartTangent() and getEndTangent() method for Polyline
  docs/api/canvas.en.md
  docs/api/canvas.zh.md
  docs/api/group.en.md
  docs/api/group.zh.md
  docs/api/shape/polyline.en.md
  docs/api/shape/polyline.zh.md
  packages/g-canvas/src/shape/polyline.ts
  packages/g-canvas/tests/unit/shape/polyline-spec.js
  packages/g-svg/src/shape/polyline.ts
  packages/g-svg/tests/unit/shape/polyline-spec.js
Labels: PR: unreviewed, enhancement

#330 feat(g-canvas): add getStartTangent() and getEndTangent() method for Path
  docs/api/shape/path.en.md
  docs/api/shape/path.zh.md
  docs/api/shape/polyline.zh.md
  examples/animation/path/demo/meta.json
  packages/g-canvas/src/shape/path.ts
  packages/g-canvas/src/shape/polyline.ts
  packages/g-canvas/src/util/path.ts
  packages/g-canvas/tests/unit/shape/image-spec.js
  packages/g-canvas/tests/unit/shape/path-spec.js
  packages/g-svg/src/shape/polyline.ts
Labels: PR: unreviewed, enhancement

#334 feat: export interface to user
  packages/g-base/src/index.ts
  packages/g-canvas/src/index.ts
  packages/g-svg/src/index.ts
Labels: PR: reviewed-approved, enhancement

#340 fix(g-base): sort method should work when zIndex is changed
  packages/g-base/src/abstract/element.ts
  packages/g-canvas/tests/bugs/issue-339-spec.js
Labels: PR: reviewed-changes-requested, bug
