Repository antvis/G, pull requests merged in 2019-10, with the labels that each got.

#188 fix(g-canvas): context scale should be effective
  packages/g-canvas/__tests__/bugs/issue-187-spec.js
  packages/g-canvas/__tests__/mocha.opts
  packages/g-canvas/src/canvas.ts
Labels: PR: unreviewed, bug

#190 fix(g-canvas): autoDraw should be true by default
  packages/g-canvas/__tests__/unit/canvas-spec.js
  packages/g-canvas/src/canvas.ts
Labels: PR: unreviewed, bug

#192 fix(g-svg): autoDraw should be true and immutable to avoid redundant rendering when animating
  packages/g-svg/__tests__/bugs/issue-191-spec.js
  packages/g-svg/src/canvas.ts
Labels: PR: unreviewed, bug

#194 fix(g-canvas): pixelRatio should be effective
  packages/g-base/__tests__/unit/animate-spec.js
  packages/g-canvas/__tests__/bugs/issue-187-spec.js
  packages/g-canvas/src/canvas.ts
  packages/g-svg/__tests__/bugs/issue-191-spec.js
Labels: PR: unreviewed, bug

#197 fix(build): remove postinstall script
  package.json
  packages/g-base/package.json
  packages/g-canvas/package.json
  packages/g-math/package.json
  packages/g-mobile/package.json
  packages/g-svg/package.json
  packages/g-webgl/package.json
Labels: PR: unreviewed, bug

#200 fix(g-base): animation cover
  packages/g-base/__tests__/unit/animate-spec.js
  packages/g-base/src/abstract/element.ts
Labels: PR: reviewed-approved, bug

#198 refactor(g-base): merge AbstractContainer and ContainerUtil
  packages/g-base/__tests__/unit/container-util-spec.js
  packages/g-base/src/abstract/container.ts
  packages/g-base/src/util/container.ts
Labels: PR: unreviewed, refactor

#207 [4.0] Add site skeleton for G
  .gitignore
  commitlint.config.js
  docs/api/canvas.en.md
  docs/api/canvas.zh.md
  docs/api/group.en.md
  docs/api/group.zh.md
  docs/guide/changelog.en.md
  docs/guide/changelog.zh.md
  docs/guide/getting-started.en.md
  docs/guide/getting-started.zh.md
  docs/guide/introduce.en.md
  docs/guide/introduce.zh.md
  docs/guide/render/shape.en.md
  docs/guide/render/shape.zh.md
  gatsby-browser.js
  gatsby-config.js
  package.json
  site/externals.d.ts
  site/locale.json
  site/pages/index.en.tsx
  site/pages/index.zh.tsx
  site/tsconfig.json
  site/tslint.json
  tsconfig.json
Labels: PR: unreviewed

#208 fix(g-canvas): make non-array value compatible with lineDash
  packages/g-canvas/__tests__/bugs/issue-206-spec.js
  packages/g-canvas/src/util/draw.ts
Labels: PR: unreviewed, bug

#212 fix(g-base): invertFromMatrix should be effective
  packages/g-base/src/abstract/container.ts
  packages/g-base/src/abstract/shape.ts
  packages/g-canvas/__tests__/bugs/issue-202-spec.js
Labels: PR: reviewed-changes-requested, bug

#214 build: Should run build when versions are modified and committed for lerna
  README.md
  package.json
  packages/g-base/src/animate/timeline.ts
  packages/g-base/src/util/path.ts
  packages/g-svg/src/util/format.ts
  tslint.json
Labels: PR: reviewed-changes-requested, build

#223 feat: add path array type define
  packages/g-base/src/types.ts
  packages/g-base/src/util/path.ts
Labels: PR: reviewed-approved, enhancement

#221 fix(g-svg): mouseenter and mouseleave should be effective
  packages/g-base/src/event/event-contoller.ts
  packages/g-svg/tests/bugs/issue-205-spec.js
Labels: PR: reviewed-changes-requested, bug

#224 fix(g-canvas): bbox calculation should be correct for path with arc
  packages/g-canvas/__tests__/bugs/issue-202-spec.js
  packages/g-canvas/tests/bugs/issue-222-spec.js
  packages/g-math/src/arc.ts
  packages/g-math/tests/unit/ellipse-arc-spec.js
Labels: PR: reviewed-approved, bug

#220 fix(g-canvas): clip animation should be effective
  packages/g-base/src/abstract/element.ts
  packages/g-canvas/src/shape/base.ts
  packages/g-canvas/tests/bugs/issue-202-spec.js
  packages/g-canvas/tests/bugs/issue-206-spec.js
  packages/g-canvas/tests/bugs/issue-210-spec.js
  packages/g-canvas/tests/bugs/issue-218-spec.js
Labels: PR: unreviewed, bug

#226 docs: 🆙 upgrade @antv/gatsby-theme-antv to 0.4.0
  gatsby-browser.js
  gatsby-config.js
  package.json
Labels: PR: unreviewed, documentation

#230 fix(g-base): event delegation on shape should be effective
  packages/g-base/src/event/event-contoller.ts
  packages/g-canvas/tests/bugs/issue-227-spec.js
  packages/g-canvas/tests/util.ts
Labels: PR: reviewed-changes-requested, bug

#231 fix: revert #178
  packages/g-base/src/abstract/container.ts
  packages/g-base/src/abstract/element.ts
  packages/g-base/src/abstract/shape.ts
  packages/g-base/src/bbox.ts
  packages/g-base/src/index.ts
  packages/g-base/src/interfaces.ts
  packages/g-base/src/types.ts
  packages/g-base/tests/unit/index-spec.js
  packages/g-canvas/src/index.ts
  packages/g-canvas/src/shape/base.ts
  packages/g-canvas/src/shape/text.ts
  packages/g-canvas/tests/unit/index-spec.js
  packages/g-svg/src/index.ts
  packages/g-svg/src/shape/base.ts
  packages/g-svg/tests/unit/index-spec.js
Labels: PR: reviewed-approved, bug

#234 docs: upgrade @antv/gatsby-theme-antv to 0.5.0
  package.json
  site/locale.json
  site/pages/index.zh.tsx
Labels: PR: reviewed-approved, documentation

#219 fix: add typescript definitions for shape type
  packages/g-base/src/abstract/container.ts
  packages/g-base/src/interfaces.ts
  packages/g-base/src/types.ts
  packages/g-canvas/src/canvas.ts
  packages/g-canvas/src/group.ts
  packages/g-canvas/src/index.ts
  packages/g-canvas/src/shape/index.ts
  packages/g-canvas/tests/unit/shape/index-spec.js
  packages/g-svg/src/canvas.ts
  packages/g-svg/src/group.ts
  packages/g-svg/src/index.ts
  packages/g-svg/src/shape/index.ts
  packages/g-svg/tests/unit/shape/index-spec.js
Labels: PR: unreviewed, bug

#235 使用 @antv/event-emitter 替代内置的 ee
  packages/g-base/README.md
  packages/g-base/package.json
  packages/g-base/src/abstract/base.ts
  packages/g-base/src/event/event-contoller.ts
  packages/g-base/src/interfaces.ts
  packages/g-base/tests/unit/base-spec.js
Labels: PR: reviewed-approved

#238 chore: clear incorrect README
  packages/g-canvas/README.md
  packages/g-svg/README.md
  packages/g-webgl/README.md
Labels: PR: unreviewed, chore

#239 fix(g-canvas): animation for marker should be effective
  packages/g-canvas/src/shape/marker.ts
  packages/g-canvas/tests/bugs/issue-236-spec.js
Labels: PR: reviewed-approved, bug

#241 fix(g-svg): should get correct path for marker
  packages/g-canvas/tests/bugs/issue-227-spec.js
  packages/g-svg/src/shape/marker/index.ts
  packages/g-svg/tests/bugs/issue-240-spec.js
  packages/g-svg/tests/unit/shape/marker-spec.js
Labels: PR: reviewed-approved, bug

#243 fix(g-canvas): bbox calculation should be correct for path with angle
  packages/g-canvas/src/shape/path.ts
  packages/g-canvas/src/util/path.ts
  packages/g-canvas/tests/bugs/issue-232-spec.js
Labels: PR: reviewed-changes-requested, bug

#248 chore: upgrade theme
  gatsby-config.js
  package.json
Labels: PR: reviewed-changes-requested
