Repository antvis/G, pull requests merged in 2020-05, with the labels that each got.

#508 chore(deps): bump @antv/matrix-util from 2.0.4 to 3.0.2
  packages/g-base/package.json
  packages/g-base/src/abstract/element.ts
  packages/g-canvas/tests/bugs/issue-drag-spec.js
Labels: PR: unreviewed, dependencies

#513 fix(deps): Revert "chore(deps): bump @antv/matrix-util from 2.0.4 to 3.0.2"
  packages/g-base/package.json
  packages/g-base/src/abstract/element.ts
  packages/g-canvas/tests/bugs/issue-drag-spec.js
Labels: PR: reviewed-changes-requested, bug

#517 fix(revert): revert "fix(canvas): canvas.getPointByClient() should calculate correctly when container has CSS transform"
  src/canvas.js
  src/util/index.js
  test/bugs/issue-333-spec.js
Labels: PR: reviewed-changes-requested, bug

#516 fix(g-base): event should work when CSS transform is applied
  docs/api/canvas.en.md
  docs/api/canvas.zh.md
  packages/g-base/package.json
  packages/g-base/src/abstract/canvas.ts
  packages/g-base/src/event/event-contoller.ts
  packages/g-base/src/interfaces.ts
  packages/g-canvas/tests/bugs/issue-489-spec.js
Labels: PR: unreviewed, bug

#520 fix(event): event should work when CSS transform is applied
  package.json
  src/canvas.js
  src/core/mixin/event.js
  test/bugs/issue-489-spec.js
Labels: PR: reviewed-changes-requested, bug

#522 fix(revert): revert "fix(canvas): canvas.getPointByClient() should calculate correctly when container has CSS transform"
  __tests__/bugs/issue-333-spec.js
  src/canvas.ts
Labels: PR: reviewed-changes-requested, bug

#521 chore(deps): bump @antv/matrix-util from 2.0.4 to 3.0.2
  packages/g-base/package.json
  packages/g-base/src/abstract/element.ts
  packages/g-canvas/tests/bugs/issue-drag-spec.js
Labels: PR: reviewed-changes-requested, dependencies

#524 fix(g-base): event => ev
  packages/g-base/src/abstract/canvas.ts
Labels: PR: reviewed-changes-requested, bug

#523 fix(event): event should work when CSS transform is applied
  __tests__/bugs/issue-489-spec.js
  package.json
  src/canvas.ts
Labels: PR: reviewed-changes-requested, bug

#490 Refresh prompt
  packages/g-base/package.json
  packages/g-base/src/abstract/container.ts
  packages/g-base/src/abstract/element.ts
  packages/g-base/src/abstract/shape.ts
  packages/g-base/tests/unit/bbox-spec.js
  packages/g-base/tests/unit/group-spec.js
  packages/g-base/tests/unit/shape-spec.js
  packages/g-canvas/package.json
  packages/g-canvas/src/canvas.ts
  packages/g-canvas/src/group.ts
  packages/g-canvas/src/shape/base.ts
  packages/g-canvas/src/util/draw.ts
  packages/g-canvas/src/util/hit.ts
  packages/g-canvas/src/util/path.ts
  packages/g-canvas/tests/unit/canvas-draw-spec.js
  packages/g-canvas/tests/unit/canvas-refresh-spec.js
  packages/g-canvas/tests/unit/util/quick-hit-spec.js
Labels: PR: unreviewed

#541 fix(path): should work for Path when path attr length is 1
  src/shapes/path.js
  test/bugs/issue-540-spec.js
Labels: PR: merged, bug
