Repository antvis/G, pull requests merged in 2020-01, with the labels that each got.

#346 fix(g-canvas & g-svg): opacity attr for shape should be 1 by default
  docs/api/shape/attrs.en.md
  docs/api/shape/attrs.zh.md
  packages/g-canvas/src/shape/base.ts
  packages/g-canvas/src/shape/image.ts
  packages/g-canvas/src/shape/text.ts
  packages/g-canvas/tests/bugs/issue-342-spec.js
  packages/g-svg/src/shape/base.ts
  packages/g-svg/src/shape/rect.ts
  packages/g-svg/tests/bugs/issue-342-spec.js
Labels: PR: unreviewed, bug

#347 chore: Merge code from datavis/g-3.x
  package.json
  src/core/mixin/event.js
  src/index.js
  test/unit/canvas/core/event-spec.js
Labels: PR: unreviewed, chore

#348 fix(canvas): canvas.getPointByClient() should calculate correctly when container has CSS transform
  src/canvas.js
  src/util/index.js
  test/bugs/issue-333-spec.js
Labels: PR: reviewed-changes-requested, bug

#349 fix(canvas): canvas.getPointByClient() should calculate correctly when container has CSS transform
  __tests__/bugs/issue-333-spec.js
  src/canvas.ts
Labels: PR: reviewed-changes-requested, bug

#351 fix(g-canvas): matrix attr for canvas should work correctly
  packages/g-canvas/src/canvas.ts
  packages/g-canvas/src/interfaces.ts
  packages/g-canvas/tests/bugs/issue-350-spec.js
Labels: PR: unreviewed, bug

#353 fix(g-base): mouseleave evene should be emitted from shape to outside of canvas directly
  packages/g-base/src/event/event-contoller.ts
  packages/g-canvas/tests/bugs/issue-321-spec.js
  packages/g-svg/tests/bugs/issue-205-spec.js
Labels: PR: unreviewed, bug

#355 feat(g-canvas): support arrow for Line
  packages/g-canvas/package.json
  packages/g-canvas/src/shape/line.ts
  packages/g-canvas/src/util/arrow.ts
  packages/g-canvas/tests/unit/shape/line-spec.js
Labels: PR: unreviewed, enhancement

#356 feat(g-canvas): support arrow for Polyline
  packages/g-canvas/src/shape/polyline.ts
  packages/g-canvas/src/util/arrow.ts
  packages/g-canvas/tests/unit/shape/polyline-spec.js
Labels: PR: unreviewed, enhancement

#357 feat(g-canvas): support arrow for Path
  packages/g-canvas/src/shape/marker.ts
  packages/g-canvas/src/shape/path.ts
  packages/g-canvas/src/util/arrow.ts
  packages/g-canvas/src/util/draw.ts
  packages/g-canvas/tests/unit/shape/path-spec.js
Labels: PR: unreviewed, enhancement

#361 chore(g-canvas & g-svg): give default value for some attrs for shape
  packages/g-canvas/src/shape/circle.ts
  packages/g-canvas/src/shape/ellipse.ts
  packages/g-canvas/src/shape/image.ts
  packages/g-canvas/src/shape/line.ts
  packages/g-canvas/src/shape/rect.ts
  packages/g-canvas/src/shape/text.ts
  packages/g-canvas/tests/unit/shape/image-spec.js
  packages/g-svg/src/shape/circle.ts
  packages/g-svg/src/shape/ellipse.ts
  packages/g-svg/src/shape/image.ts
  packages/g-svg/src/shape/line.ts
  packages/g-svg/src/shape/path.ts
  packages/g-svg/src/shape/polyline.ts
  packages/g-svg/src/shape/rect.ts
  packages/g-svg/src/shape/text.ts
Labels: PR: unreviewed, chore

#364 fix(g-canvas): mergeRegion util function should work correctly
  packages/g-canvas/src/util/util.ts
Labels: PR: unreviewed, bug

#365 fix(g-svg): clip animation should work
  packages/g-base/src/animate/timeline.ts
  packages/g-svg/src/canvas.ts
  packages/g-svg/src/defs/clip.ts
  packages/g-svg/src/group.ts
  packages/g-svg/src/interfaces.ts
  packages/g-svg/src/shape/base.ts
  packages/g-svg/src/shape/rect.ts
  packages/g-svg/src/util/dom.ts
  packages/g-svg/src/util/draw.ts
  packages/g-svg/tests/bugs/issue-359-spec.js
Labels: PR: unreviewed, bug

#366 feat(drag): support canvas drag
  packages/g-base/package.json
  packages/g-base/src/event/event-contoller.ts
  packages/g-base/tests/unit/event-spec.js
Labels: PR: reviewed-approved, enhancement

#368 fix(g-canvas): path with relative command should work for marker
  packages/g-canvas/src/shape/marker.ts
  packages/g-canvas/tests/bugs/issue-367-spec.js
Labels: PR: unreviewed, bug

#371 fix(g-base): mouseup and click event should not be emitted when contextmenu emitted
  packages/g-base/src/event/event-contoller.ts
  packages/g-canvas/tests/bugs/issue-370-spec.js
Labels: PR: reviewed-changes-requested, bug

#373 fix(g-base): should handle mousedown resulted from contextmenu event
  packages/g-base/src/event/event-contoller.ts
Labels: PR: reviewed-changes-requested, bug

#374 feat(drag): drag out canvas
  packages/g-base/src/event/event-contoller.ts
  packages/g-base/src/event/graph-event.ts
  packages/g-base/src/types.ts
  packages/g-base/tests/unit/event-spec.js
  packages/g-canvas/tests/bugs/issue-drag-spec.js
Labels: PR: reviewed-approved, enhancement

#376 feat(drag): drop on canvas
  packages/g-base/src/event/event-contoller.ts
  packages/g-base/tests/unit/event-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#377 fix(g-canvas): opacity attr should be composite with parent
  packages/g-base/src/abstract/element.ts
  packages/g-canvas/src/canvas.ts
  packages/g-canvas/src/shape/base.ts
  packages/g-canvas/src/util/draw.ts
  packages/g-canvas/tests/bugs/issue-358-spec.js
  packages/g-svg/src/shape/base.ts
  packages/g-svg/src/shape/rect.ts
Labels: PR: reviewed-changes-requested, bug
