Repository antvis/G, pull requests merged in 2020-03, with the labels that each got.

#435 fix(text): no rendering for text in IE when maxWidth is nil
  __tests__/unit/canvas/shape/text-spec.js
  src/shapes/text.ts
Labels: bug

#437 fix(g-base): should consider precision of angle calculation for Path
  packages/g-base/src/bbox/path.ts
  packages/g-canvas/tests/bugs/issue-436-spec.js
Labels: PR: reviewed-changes-requested, bug

#440 feat(g-base): 补充 ShapeAttrs 类型定义
  packages/g-base/src/types.ts
Labels: PR: reviewed-changes-requested, enhancement

#438 fix(g-canvas): g-canvas@0.3.29 is not compatible with @antv/path-util…
  packages/g-canvas/package.json
Labels: PR: unreviewed, bug

#445 fix(refresh): fixed bug #444
  packages/g-canvas/src/canvas.ts
  packages/g-canvas/tests/bugs/issue-444-spec.js
Labels: PR: reviewed-changes-requested, bug

#446 fix(g-canvas): fill attr should work for custom arrow
  packages/g-canvas/src/util/arrow.ts
Labels: PR: reviewed-changes-requested, bug
