Repository antvis/G, pull requests merged in 2020-06, with the labels that each got.

#550 fix(g-canvas): render should work correctly when element is clipped by view
  package.json
  packages/g-canvas/src/canvas.ts
  packages/g-canvas/src/group.ts
  packages/g-canvas/src/shape/base.ts
  packages/g-canvas/tests/bugs/issue-380-spec.js
  packages/g-canvas/tests/bugs/issue-456-spec.js
  packages/g-canvas/tests/bugs/issue-494-spec.js
Labels: PR: unreviewed, bug

#561 feat(canvas): Support context and offscreenCanvas props for non-browser env
  __tests__/bugs/issue-556-spec.js
  src/canvas.ts
  src/core/base.ts
  src/renderers/canvas/painter.ts
  src/shapes/util/is-point-in-path-by-ctx.ts
Labels: PR: unreviewed, enhancement

#574 Pixel ratio v0.4
  packages/g-canvas/src/canvas.ts
  packages/g-canvas/tests/unit/canvas-spec.js
Labels: PR: reviewed-changes-requested
