Repository antvis/G, pull requests merged in 2020-04, with the labels that each got.

#450 refactor: use unpkg other than browser field in package.json
  packages/g-canvas/package.json
  packages/g-mobile/package.json
  packages/g-svg/package.json
  packages/g-webgl/package.json
Labels: PR: partially-approved, refactor

#449 fix(g-base): fix an condition judgement type error in path util
  packages/g-base/src/util/path.ts
Labels: PR: reviewed-changes-requested, bug

#448 feat(delegation): delegation mouseenter, mouseleave
  packages/g-base/src/abstract/element.ts
  packages/g-base/src/event/event-contoller.ts
  packages/g-base/src/util/util.ts
  packages/g-base/tests/unit/event-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#458 feat(pixelratio): round pixelRatio
  packages/g-canvas/src/canvas.ts
  packages/g-canvas/tests/unit/canvas-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#460 fix(g-base): dragenter & dragleave event should be able to bubble
  packages/g-base/src/event/event-contoller.ts
  packages/g-canvas/tests/bugs/issue-456-spec.js
Labels: PR: reviewed-changes-requested, bug

#463 fix(g-svg): toFront() method should work
  packages/g-svg/src/util/dom.ts
  packages/g-svg/tests/bugs/issue-462-spec.js
Labels: PR: reviewed-changes-requested, bug

#466 fix(g-svg): should not handle fontSize < 12 for text
  packages/g-svg/src/shape/text.ts
  packages/g-svg/tests/bugs/issue-465-spec.js
Labels: PR: reviewed-changes-requested, bug

#464 fix(g-base): set animation._paused to true in element.pauseAnimate()
  packages/g-base/src/abstract/element.ts
Labels: PR: reviewed-approved, bug

#469 fix: prevent undefined error when check isParent
  packages/g-base/src/abstract/element.ts
Labels: PR: reviewed-changes-requested, bug

#470 fix: 添加空判断，防止报错
  packages/g-base/src/abstract/element.ts
Labels: PR: reviewed-changes-requested, bug

#467 Refresh bbox
  packages/g-canvas/src/canvas.ts
  packages/g-canvas/src/util/draw.ts
  packages/g-canvas/tests/unit/canvas-draw-spec.js
  packages/g-canvas/tests/unit/util/draw-spec.js
Labels: PR: reviewed-changes-requested

#471 refactor: remove some unused code
  packages/g-base/src/abstract/base.ts
  packages/g-base/src/abstract/canvas.ts
  packages/g-base/src/abstract/element.ts
  packages/g-base/src/abstract/group.ts
  packages/g-base/src/bbox/util.ts
  packages/g-base/src/event/event-contoller.ts
Labels: PR: reviewed-approved, refactor

#472 refactor: export Math function
  packages/g-canvas/src/util/arrow.ts
Labels: PR: reviewed-changes-requested, refactor

#473 refactor: import @antv/g-base getOffScreenContext
  packages/g-canvas/src/shape/text.ts
  packages/g-canvas/src/util/in-path/point-in-path.ts
  packages/g-canvas/src/util/util.ts
Labels: PR: reviewed-approved, refactor

#474 refactor: replace line box function with getBBoxByArray
  packages/g-math/src/line.ts
Labels: PR: reviewed-changes-requested, refactor

#477 Refactor(g-svg): add createSVGElement function
  packages/g-svg/src/canvas.ts
  packages/g-svg/src/defs/arrow.ts
  packages/g-svg/src/defs/clip.ts
  packages/g-svg/src/defs/gradient.ts
  packages/g-svg/src/defs/index.ts
  packages/g-svg/src/defs/pattern.ts
  packages/g-svg/src/defs/shadow.ts
  packages/g-svg/src/group.ts
  packages/g-svg/src/util/dom.ts
Labels: PR: reviewed-changes-requested, refactor

#475 feat: g-math add getBBoxRange
  packages/g-math/src/util.ts
  packages/g-math/tests/unit/util-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#478 feat(getshape): quick hit in canvas
  packages/g-base/src/abstract/base.ts
  packages/g-base/src/abstract/container.ts
  packages/g-base/src/abstract/element.ts
  packages/g-base/src/interfaces.ts
  packages/g-base/src/util/box.ts
  packages/g-base/src/util/util.ts
  packages/g-canvas/src/canvas.ts
  packages/g-canvas/src/shape/base.ts
  packages/g-canvas/src/util/hit.ts
  packages/g-canvas/tests/unit/shape/image-spec.js
  packages/g-canvas/tests/unit/util/hit-spec.js
  packages/g-canvas/tests/unit/util/quick-hit-spec.js
Labels: PR: reviewed-approved, enhancement

#480 feat(delegate): name support array
  packages/g-base/src/abstract/element.ts
  packages/g-base/tests/unit/event-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#481 fix(canvas): getCanvasBBox removed
  packages/g-canvas/package.json
  packages/g-canvas/src/canvas.ts
Labels: PR: reviewed-changes-requested, bug

#483 fix(gl-matrix): use gl-matrix instead of antv/gl-matrix
  packages/g-base/package.json
  packages/g-canvas/package.json
  packages/g-canvas/src/util/path.ts
  packages/g-math/package.json
  packages/g-math/src/line.ts
Labels: PR: reviewed-changes-requested, bug

#484 fix(hit): canvas is not a group
  packages/g-canvas/src/util/hit.ts
Labels: PR: reviewed-changes-requested, bug

#487 chore: 🔀 add GitHub Action to sync Gitee
  .github/workflows/mirror.yml
Labels: PR: reviewed-approved, chore

#491 fix(g-canvas): Add override of clearEvents()
  packages/g-base/src/abstract/canvas.ts
  packages/g-base/tests/unit/event-spec.js
  packages/g-canvas/src/canvas.ts
  packages/g-svg/src/canvas.ts
Labels: PR: reviewed-approved, bug
