Repository antvis/G, pull requests merged in 2020-02, with the labels that each got.

#379 fix(mouseleave): fixed bug of mouseleave
  packages/g-base/src/event/event-contoller.ts
  packages/g-canvas/tests/bugs/issue-drag-spec.js
  packages/g-canvas/tests/bugs/issue-mouseleave-spec.js
Labels: PR: reviewed-changes-requested, bug

#381 fix(g-base): should emit drag event for canvas only when draggable is true
  packages/g-base/src/event/event-contoller.ts
  packages/g-base/tests/unit/event-spec.js
  packages/g-canvas/tests/bugs/issue-380-spec.js
Labels: PR: unreviewed, bug

#383 feat(event): add mousewheel event
  packages/g-base/src/abstract/canvas.ts
  packages/g-base/src/event/event-contoller.ts
  packages/g-base/tests/unit/canvas-spec.js
  packages/g-base/tests/unit/event-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#385 feat(g-base): add setZIndex method for Element
  docs/api/general/element.en.md
  docs/api/general/element.zh.md
  packages/g-base/src/abstract/container.ts
  packages/g-base/src/abstract/element.ts
  packages/g-base/src/interfaces.ts
  packages/g-canvas/tests/bugs/issue-384-spec.js
Labels: PR: reviewed-changes-requested, enhancement

#389 feat(g-base): add transform related method
  docs/api/general/element.en.md
  docs/api/general/element.zh.md
  docs/guide/release.en.md
  docs/guide/release.zh.md
  packages/g-base/package.json
  packages/g-base/src/abstract/element.ts
  packages/g-base/src/interfaces.ts
  packages/g-base/tests/unit/element-spec.js
  packages/g-canvas/tests/bugs/issue-204-spec.js
Labels: enhancement

#390 fix(g-canvas & g-svg): should be compatible with radius attr for Marker
  packages/g-canvas/src/shape/marker.ts
  packages/g-svg/src/shape/marker/index.ts
Labels: bug

#391 fix(g-base): compatible with previous onFrame usage and function cannot be interpolated
  packages/g-base/src/abstract/element.ts
  packages/g-base/src/animate/timeline.ts
  packages/g-base/tests/unit/animate-spec.js
Labels: bug

#393 fix(g-canvas): should work when r attr is 0 for Marker
  packages/g-canvas/src/shape/marker.ts
  packages/g-canvas/tests/bugs/issue-392-spec.js
Labels: bug

#394 fix(g-svg): remove for clipShape should work
  packages/g-base/src/abstract/element.ts
  packages/g-base/tests/unit/element-spec.js
  packages/g-canvas/tests/bugs/issue-218-spec.js
  packages/g-svg/src/util/draw.ts
  packages/g-svg/tests/bugs/issue-388-spec.js
Labels: bug

#396 fix(g-svg): matrix animation for group should work
  packages/g-svg/src/group.ts
  packages/g-svg/src/util/svg.ts
  packages/g-svg/tests/bugs/issue-388-spec.js
Labels: bug

#397 fix(g-svg): opacity attr for Rect should work
  packages/g-svg/src/shape/circle.ts
  packages/g-svg/src/shape/rect.ts
  packages/g-svg/tests/bugs/issue-388-spec.js
Labels: bug

#398 fix(g-svg): null for fill and stroke attr should work
  packages/g-svg/src/shape/base.ts
  packages/g-svg/tests/bugs/issue-388-spec.js
Labels: bug

#399 feat(g-base): add getChildByIndex, contain and removeChild method for Container
  docs/api/general/container.en.md
  docs/api/general/container.zh.md
  packages/g-base/src/abstract/container.ts
  packages/g-base/src/interfaces.ts
  packages/g-base/tests/unit/group-spec.js
Labels: enhancement

#403 fix(g-base): canvas matrix change should affect totalMatrix of its children
  packages/g-base/src/abstract/container.ts
  packages/g-base/src/abstract/group.ts
  packages/g-canvas/tests/bugs/issue-402-spec.js
Labels: bug

#404 fix(g-base): should use ev object from upstream instead of global event
  packages/g-base/src/event/event-contoller.ts
Labels: bug

#408 fix(g-base): bbox for container should not contain Infinity and -Infinity
  packages/g-base/src/abstract/container.ts
  packages/g-canvas/tests/bugs/issue-407-spec.js
Labels: bug

#409 fix(g-svg): should not create marker defs dom when startArrow or endArrow is false
  packages/g-svg/src/shape/line.ts
  packages/g-svg/src/shape/path.ts
  packages/g-svg/tests/unit/defs/arrow-spec.js
Labels: bug

#410 fix(g-base): #408 PR
  packages/g-base/src/abstract/container.ts
  packages/g-canvas/tests/bugs/issue-407-spec.js
Labels: bug

#411 fix(svg): should not generate svg elements repeatedly when canvas.draw()
  packages/g-svg/src/canvas.ts
  packages/g-svg/src/defs/index.ts
  packages/g-svg/src/group.ts
  packages/g-svg/src/interfaces.ts
  packages/g-svg/src/shape/base.ts
  packages/g-svg/src/util/draw.ts
  packages/g-svg/tests/bugs/issue-191-spec.js
  packages/g-svg/tests/bugs/issue-388-spec.js
Labels: bug

#414 fix(g-svg): should work when autoDraw is false
  packages/g-svg/src/group.ts
  packages/g-svg/src/interfaces.ts
  packages/g-svg/src/shape/base.ts
  packages/g-svg/tests/bugs/issue-388-spec.js
Labels: bug

#415 fix(g-svg): default arrow rendering should be same with Canvas
  packages/g-svg/src/defs/arrow.ts
  packages/g-svg/tests/unit/defs/arrow-spec.js
Labels: bug

#418 Add box
  packages/g-base/package.json
  packages/g-base/src/abstract/element.ts
  packages/g-base/src/bbox/circle.ts
  packages/g-base/src/bbox/ellipse.ts
  packages/g-base/src/bbox/index.ts
  packages/g-base/src/bbox/line.ts
  packages/g-base/src/bbox/path.ts
  packages/g-base/src/bbox/points.ts
  packages/g-base/src/bbox/rect.ts
  packages/g-base/src/bbox/register.ts
  packages/g-base/src/bbox/text.ts
  packages/g-base/src/types.ts
  packages/g-base/src/util/offscreen.ts
  packages/g-base/src/util/text.ts
  packages/g-base/tests/unit/bbox-spec.js
  packages/g-base/tests/unit/util-spec.js
  packages/g-canvas/src/shape/base.ts
  packages/g-canvas/src/shape/circle.ts
  packages/g-canvas/src/shape/ellipse.ts
  packages/g-canvas/src/shape/image.ts
  packages/g-canvas/src/shape/line.ts
  packages/g-canvas/src/shape/marker.ts
  packages/g-canvas/src/shape/path.ts
  packages/g-canvas/src/shape/polygon.ts
  packages/g-canvas/src/shape/polyline.ts
  packages/g-canvas/src/shape/rect.ts
  packages/g-canvas/src/shape/text.ts
  packages/g-canvas/src/util/path.ts
  packages/g-canvas/tests/bugs/issue-206-spec.js
  packages/g-canvas/tests/bugs/issue-222-spec.js
  packages/g-canvas/tests/unit/shape/path-spec.js
  packages/g-canvas/tests/unit/util/path-spec.js
  packages/g-svg/src/shape/base.ts
  packages/g-svg/tests/unit/defs/arrow-spec.js
  packages/g-svg/tests/unit/shape/circle-spec.js
  packages/g-svg/tests/unit/shape/path-spec.js
  packages/g-svg/tests/unit/shape/text-spec.js
Labels: WIP

#419 fix(bbox): string functions error
  packages/g-base/package.json
  packages/g-base/src/util/text.ts
  packages/g-base/tests/unit/bbox-spec.js
Labels: bug

#420 fix(g-base): bbox calculation should be correct for container, …
  packages/g-base/src/abstract/container.ts
  packages/g-canvas/tests/bugs/issue-407-spec.js
Labels: bug

#421 fix(g-canvas): matrix of element should affect its clip
  packages/g-canvas/src/group.ts
  packages/g-canvas/src/shape/base.ts
  packages/g-canvas/tests/bugs/issue-382-spec.js
Labels: bug

#423 fix(g-canvas): should render when localRefresh change from false to true
  packages/g-canvas/src/canvas.ts
  packages/g-canvas/src/util/draw.ts
  packages/g-canvas/tests/bugs/issue-422-spec.js
Labels: bug

#424 fix(g-base): delay and repeat should work in toAttrs for animate method
  packages/g-base/src/abstract/element.ts
  packages/g-base/tests/unit/animate-spec.js
Labels: bug

#427 fix(g-base): delay should not work in toAttrs
  packages/g-base/src/abstract/element.ts
  packages/g-base/tests/unit/animate-spec.js
Labels: bug

#430 fix(g-svg): event should work when matrix is applied
  packages/g-base/src/abstract/container.ts
  packages/g-base/src/event/event-contoller.ts
  packages/g-base/src/interfaces.ts
  packages/g-svg/src/canvas.ts
  packages/g-svg/tests/bugs/issue-428-spec.js
  packages/g-svg/tests/util.ts
Labels: bug

#434 feat(bbox): shadow refresh
  packages/g-base/package.json
  packages/g-base/src/abstract/shape.ts
  packages/g-base/src/types.ts
  packages/g-base/tests/unit/bbox-spec.js
  packages/g-canvas/tests/bugs/issue-shadow-spec.js
Labels: enhancement
