Repository antvis/G, pull requests merged in 2021-04, with the labels that each got.

#751 fix(g-mobile): get globalAlpha problem in mini program
  packages/g-mobile/src/util/mini-canvas-proxy.ts
Labels: PR: reviewed-approved

#757 fix: mini-program canvas proxy problem
  packages/g-mobile/src/util/mini-canvas-proxy.ts
Labels: PR: reviewed-approved

#755 fix: remove padding when calc bbox of Text
  packages/g-base/package.json
  packages/g-base/src/bbox/text.ts
  packages/g-base/src/index.ts
Labels: PR: reviewed-approved

#752 fix(text-shape): 修复文本 shape，绘制了 null
  packages/g-canvas/src/shape/text.ts
  packages/g-canvas/tests/unit/shape/text-spec.js
Labels: PR: partially-approved

#758 fix: 直接透传scale
  packages/g-mobile/src/events.ts
Labels: PR: reviewed-approved

#759 0.5.9 版本号升级
  packages/g-base/package.json
  packages/g-base/src/index.ts
Labels: PR: unreviewed

#762 chore: 0.5.8
  packages/g-canvas/package.json
  packages/g-canvas/src/index.ts
Labels: PR: unreviewed

#763 chore: 0.5.9
  packages/g-canvas/package.json
  packages/g-canvas/src/index.ts
Labels: PR: unreviewed

#761 fix: util dependence version
  packages/g-base/package.json
Labels: PR: reviewed-approved

#764 chore: 0.5.10
  packages/g-canvas/package.json
  packages/g-canvas/src/index.ts
Labels: PR: reviewed-approved

#765 fix: 修复text为 0 的时候，导致不渲染
  packages/g-canvas/src/shape/text.ts
  packages/g-canvas/tests/unit/shape/text-spec.js
Labels: PR: reviewed-approved
